# Put the LBRY channel URL here
# You can find it by going to a channel and clicking the "about" tab
channels:
- lbry://@rossmanngroup#a
- lbry://@AlphaNerd#8
- lbry://@DistroTube#2
- lbry://@BrodieRobertson#5
- lbry://@fireship#6
- lbry://@bigclivedotcom#0d
- lbry://@serpentza#5
- lbry://@freakinreviews#4
- lbry://@Thoughty2#b
- lbry://@ElectroBOOM#9
- lbry://@whiteboardcrypto#5
- lbry://@Coldfusion#f
- lbry://@brightsunfilms#5
- lbry://@EposVox#6
- lbry://@veritasium#f

# Will only download last x amount of videos according to the following value
max_vids: 5
# Max disk usage allowed in GB
# Older videos will be deleted, set to 0 to disable
max_disk_usage: 0
# At which percent should older videos be deleted
usage_percent: 90
# Videos from these channels will not be deleted when disk is near capacity
never_delete:
- lbry://@rossmanngroup#a

# Only the blobs are required for seeding, clean downloads each time the script is run.
clear_downloads: true
# If you are using docker then leave this as /home/lbrynet/
lbrynet_home: /home/lbrynet/
